
#Ammo blast breaks the block.
[explosion]
	#Ammo blast breaks the block, when this setting is true.
	Break_Blocks = false

#Erase the shadow of the sliding door.
[anti_shadow]
	#Erase the shadow of the sliding door by light value 1.
	Anti_Shadow = true

#Generation and chance of BauxiteOre.
[ore_gene]
	#BauxiteOre will be generated, when this setting is true.
	Ore_Generate = true
	#RedStone Ore=8, Gold Ore=2, Diamond Ore=1
	#Range: 1 ~ 50
	Generate_Chance = 8

#Generation and chance of CherryBiome.
[biome_cherry]
	#CherryBiome will be generated, when this setting is true.
	CherryBiome_Generate = true
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	CherryBiome_Chance = 2
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	CherryTree_Chance = 2

#Generation and chance of AcerBiome.
[biome_acer]
	#AcerBiome will be generated, when this setting is true.
	AcerBiome_Generate = false
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	AcerBiome_Chance = 2
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	AcerTree_Chance = 2

#Generation and chance of GinkgoBiome.
[biome_ginkgo]
	#GinkgoBiome will be generated, when this setting is true.
	GinkgoBiome_Generate = false
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	GinkgoBiome_Chance = 2
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	GinkgoTree_Chance = 2

#Chestnuts fall from Autumn leaves.
[chestnuts_fall]
	#Chestnuts fall from Autumn leaves, when this setting is true.
	Chestnuts_Fall = false

#Use a MAKIMONO block.
[use_makimono]
	#You can use MAKIMONO block, when this setting is true.
	Use_MAKIMONO = true

